"""add_logo_url_allow_exprimetns_into_projects

Revision ID: 0d3e58a6814d
Revises: 550e54dca953
Create Date: 2026-08-31 21:13:07.415192

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d3e58a6814d'
down_revision: str | Sequence[str] | None = '550e54dca953'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('allow_experimental_functions', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'allow_experimental_functions')
    op.drop_column('projects', 'logo_url')
    # ### end Alembic commands ###
